/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthDtoSignin
 */
export interface AuthDtoSignin {
    /**
     * 
     * @type {string}
     * @memberof AuthDtoSignin
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AuthDtoSignin
     */
    'password': string;
}

