/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskUpdate
 */
export interface TaskUpdate {
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdate
     */
    'description': string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskUpdate
     */
    'isCompleted': boolean;
}

